// Auth
export const LOGIN_FETCH_SUCCESS = 'LOGIN_FETCH_SUCCESS';
export const REGISTER_FETCH_SUCCESS = 'REGISTER_FETCH_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';

// User
export const UPLOAD_CAR_AD_FETCH_SUCCESS = 'UPLOAD_CAR_AD_FETCH_SUCCESS';
